### ISSUE TITLE
Set Ability with Luminescent Platinum randomized

### ISSUE THREAD

**Issue by ElChusky** [TalonSabre/PKLumiHex#5]
Some friends and I were playing Luminescent randomized with Imposter's Ordeal randomizer.
We have Pokemons' abilities randomized, so they dont have their normal abilities.
If we try to change the pokemon's ability in PKLumiHex, it changes to the Pokemon's normal ability.

I would like to be able to change the Pokemon's ability in randomized Luminescent.
I know it is probably impossible to show in PKLumiHex the correct randomized ability name, but maybe changing only the index from the possible abilities so when I go into the game, it doesnt have the normal ability but the one randomize in the same index.

**Comment by TalonSabre** [comment]
You can also create a batch file (.bat) to run pklumi in hax mode.
Create a text file, and put this in:
`start pklumihex hax
exit 0`
Then click file > Save As...
Make sure under the file name you select "All files (*.*)"

**Comment by Thebigone4urn** [comment]
Yo could anyone help me set this up pls.
