### ISSUE TITLE
Set Up

### ISSUE THREAD

**Issue by Thebigone4urn** [TalonSabre/PKLumiHex#7]
Hi can you help with the et up of pklumihex.

**Comment by TalonSabre** [comment]
There is no set-up involved. Just extract the files into a folder and run the executable.

The batch file to run hax mode is available on the release page as well, if you want that. It goes in the same folder as the other extracted files, and serves as an alternative to using the exe.

If you are having trouble extracting the files, you'll should use google, or your preferred search engine, for help, as the exact steps vary between operating systems.

Apologies for the (very) late reply. I hope you have already solved the issue you were experiencing, and if not, I hope this helps.
